# Generated by Django 4.1.4 on 2022-12-22 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SessionYearModel',
            new_name='SessionYear',
        ),
    ]
