# Generated by Django 4.1.4 on 2022-12-22 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_sessionyearmodel_sessionyear'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professor',
            options={'verbose_name': 'Professor', 'verbose_name_plural': 'Professors'},
        ),
    ]
